clean: true
objc: true		
umbrella_header: MBPayments/MBPayments.h
framework_root: MBPayments
readme: Readme.md
module_version: 0.0.1
sdk: iphonesimulator

author: Mumble
author_url: https://mumbleideas.it/
github_url: https://github.com/Mumble-SRL/MBPayments-Objc

theme: jony
